### ISSUE TITLE
Missing crosshair target, bomb and mine sprites

### ISSUE THREAD

**Issue by akx** [suomipelit/ultimatetapankaikki#131]
The end of the targeting line should have a graphic (https://github.com/suomipelit/ultimatetapankaikki/blob/master/EFPS/TARGET.PNG) but it doesn't.

# broken

![screenshot 2019-01-31 at 11 32 09](https://user-images.githubusercontent.com/58669/52047974-ddc91680-2552-11e9-8c70-bd5559046228.png)

**Comment by veikkos** [comment]
Also missing on Windows.

**Comment by akx** [comment]
Fixed in #132. Should probably do a 1.0.1 release?
