### ISSUE TITLE
Editor?

### ISSUE THREAD

**Issue by LaraSQP** [suomipelit/ultimatetapankaikki#190]
Thank you for taking the time to port this great game and for making it all available for free.

There was an editor originally but it seems to be missing. My fault?

Would you also happen to know what happened to the repository of user-built levels?

Thanks again.

**Comment by akheron** [comment]
The original editor source code was never found. The editor would need to be recreated from scratch.

I think the original authors still have the level repository somewhere. It also includes levels for newer versions of the game.

**Comment by LaraSQP** [comment]
Much appreciated.
