### ISSUE TITLE
Multiplayer "DM Levels" episode crashes on startup

### ISSUE THREAD

**Issue by veikkos** [suomipelit/ultimatetapankaikki#32]
Start multiplayer with default settings (see below). Click Start Game again in next screen.

![multiplayer-default](https://user-images.githubusercontent.com/24453333/49539696-eeed0280-f8d6-11e8-87ad-27e016f5116a.png)

Game crashes to `Floating point exception`. Other episodes like "Blanket" works.

**Comment by akheron** [comment]
Fixed by #35
