### ISSUE TITLE
Game is rendered 320x200 instead of 320x240

### ISSUE THREAD

**Issue by veikkos** [suomipelit/ultimatetapankaikki#60]
Original game ~changes~ _can change_ resolution from 320x200 to 320x240 during actual game play if supported. Currently this port is rendering everything at 320x200.

![kuva](https://user-images.githubusercontent.com/24453333/50377466-78fed000-0626-11e9-974a-ace73e5c2f66.png)
DOSBox rendering 320x240 on top.

**Comment by akx** [comment]
I believe the original version _can_ change resolution to 320x240 if VESA/VBE is detected.

If it always changed to 320x240 and expected as much, the GUI elements at the bottom would not be visible in our version.

**Comment by veikkos** [comment]
Fixed with #65 .
