### ISSUE TITLE
Simultaneously joining network clients can break the game

### ISSUE THREAD

**Issue by veikkos** [suomipelit/ultimatetapankaikki#70]
Issue is in original TK code, not in port.

If client joins to game but waits in "game info" (see below) it doesn't yet update "enabled" status of a new player on server side. Player only gets enabled when clients starts to send alive-messages which only happens during actual gameplay.

![joining_game](https://user-images.githubusercontent.com/24453333/50487947-de790500-0a08-11e9-8aaa-89bfe4d2594c.PNG)

If another player joins during one being in screen above, same player index is assigned by the server to new client. This leads to various panics and broken game.

Best fix might be to start sending alive-messages already in joining screen - but that still needs to be validated.

**Comment by akheron** [comment]
Fixed in #106
