### ISSUE TITLE
Pressing space should toggle the map

### ISSUE THREAD

**Issue by akheron** [suomipelit/ultimatetapankaikki#81]
Map is bound to `M` currently.

According to original README and testing on DosBox, space toggles the map in v1.21.

**Comment by veikkos** [comment]
Should also check 'F' (FPS counter), 'E'/F12 (Screen-shot), right?

**Comment by akheron** [comment]
`F` and `F12` already work. #85 fixes `E` to not capture a screenshot (it does not in the original).
