### ISSUE TITLE
Player names in OPTIONS.CFG are not the same as in original

### ISSUE THREAD

**Issue by akheron** [suomipelit/ultimatetapankaikki#83]
In v1.21 player 1 is `PHUCKA` and player 2 is `RUNKHA`.

**Comment by veikkos** [comment]
Maybe also worth checking at the same time that other settings like button configs and game settings are same.

**Comment by akheron** [comment]
> I guess we can just copy the OPTIONS.CFG from TK321 and be done with it?

No we can't anymore, because it now contains SDL scancodes, whereas the one in TK321 contains TK keycodes.

**Comment by akheron** [comment]
Fixed in #99
